# Generated by Django 3.0.3 on 2020-09-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ligacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddd_origem', models.IntegerField()),
                ('ddd_destino', models.IntegerField()),
                ('tempo', models.FloatField()),
                ('plano_falemais', models.CharField(max_length=12)),
            ],
        ),
    ]
