# Generated by Django 3.0.3 on 2020-09-07 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FaleMais', '0002_auto_20200907_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarifa',
            old_name='destino',
            new_name='DDD_destino',
        ),
        migrations.RenameField(
            model_name='tarifa',
            old_name='origem',
            new_name='DDD_origem',
        ),
    ]
