# Generated by Django 3.0.3 on 2020-09-07 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FaleMais', '0004_auto_20200907_1924'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ligacao',
        ),
    ]
