# Generated by Django 3.0.3 on 2020-09-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaleMais', '0005_delete_ligacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ligacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DDD_origem', models.CharField(choices=[('011', '011'), ('016', '016'), ('017', '017'), ('018', '018')], max_length=3)),
                ('DDD_destino', models.CharField(choices=[('011', '011'), ('016', '016'), ('017', '017'), ('018', '018')], max_length=3)),
                ('tempo', models.FloatField()),
                ('plano_falemais', models.CharField(choices=[(30, 'FaleMais 30'), (60, 'FaleMais 60'), (120, 'FaleMais 120')], max_length=12)),
            ],
        ),
    ]
